---
# tasks file for node_exporter
- name: copy prometheus binary
  ansible.builtin.unarchive:
    src: node_exporter-1.1.2.linux-amd64.tar.gz
    dest: /opt/prometheus

- name: configure systemd file
  ansible.builtin.copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'

- name: enable and start service
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: yes

- name: modify filesd based on inventory
  template:
    src: filesd.yml.j2
    dest: /opt/prometheus/prometheus/filesd.yml
  notify: 
  - Restart Prometheus
