---
# tasks file for node_exporter
- name: create prometheus user
  ansible.builtin.user:
    name: prometheus
 
- name: create prometheus dir
  ansible.builtin.file:
    path: /opt/prometheus
    state: directory
    mode: 0755

- name: copy prometheus binary
  ansible.builtin.unarchive:
    src: node_exporter-1.1.2.linux-amd64.tar.gz
    dest: /opt/prometheus

- name: configure systemd file
  ansible.builtin.copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'

- name: enable and start service
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: yes

- name: modify hosts file based on inventory
  when: inventory_hostname in groups['monitoring']
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: modify filesd based on inventory
  when: inventory_hostname in groups['monitoring']
  template:
    src: filesd.yml.j2
    dest: /opt/prometheus/prometheus/filesd.yml
  notify: 
  - Restart Prometheus
